코드리뷰이후 개선
doria-re/drinkmorewater pull request #1
Opened 2022-01-29 09:27 UTC by doria-re

1. js파일을 하나로 모았습니다
2. 자주 사용하는 숫자를 변수로 선언했습니다.
3. currentUnit을 확인하기 위해 .unit의 2번째 태그의 innertext인 "컵"을 사용했습니다. 
만약 이번 경우와 다르게 단위가 따로 태그로 존재하지 않을 때는 어떻게 확인하여 비교할지 고민 예정입니다.
4. InnerText 자체를 바꾸며 변경되던 문제를 개선하기 위해 waterAmount를 선언하여 사용했습니다.
5. 마찬가지로 localStorage의 값을 직접적으로 바꾸기보다는 localWaterAmount와 newLocalWaterAmount를 사용해서 값을 계산 후 저장하는 방식으로 개선했습니다.

2022-01-29 10:36 UTC, Puterism requested changes
첫 PR까지 올리시느라 수고 많으셨어요! 👏👏👏
몇 가지 피드백을 추가로 드렸으니 확인 후에 수정 부탁드릴게요!

PR에서 Reviewer에 제 아이디 (Puterism)을 추가하고 Request review를 주시면 제게 리뷰를 요청할 수 있으니 참고 부탁드릴게요!

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +const ONE_CUP = 200;
👍  리뷰 반영 감사드려요!

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +    if (currentUnit === "컵"){
`currentUnit`에 대해서도 `innerText`의 사용을 줄이는 방법에 대해서 고민해보면 좋을 것 같아요!

힌트를 조금 드리자면 단위를 보여주는 html 요소를 하나 더 만들어서 그 안에서 보여주는 것도 방법이 될 수 있을 것 같아요

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +getWater();
코드를 합치는 과정에서 `getWater()`가 중간에 들어가게 되었다고 생각하고 있어요. 하지만 짚고 넘어가는 게 좋을 것 같아서 피드백 하나만 드릴게요

함수나 변수의 정의를 상단에, 그리고 실행하는 부분(`addEventListener` 포함)은 하단에 놓으면 코드의 흐름을 읽기 더 좋을 것 같아요! 한번 정리 부탁드릴게요 🙏

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +        newLocalWaterAmount = localWaterAmount + (waterAmount*ONE_CUP);
`newLocalWaterAmount`가 전역에서 선언되어 있는데요
각 함수가 한 번 실행 될 때마다 각각 다른 값이 한 번씩만 할당해서 사용하고, 그 뒤로는 더 이상 사용하지 않는 것으로 보여요.
해당 변수를 전역에 선언해서 사용하는 것보다, 각 함수 내에서 선언해서 각각 사용해주는 게 더 좋을 것 같아요!

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +        newLocalWaterAmount = localWaterAmount + (waterAmount*ONE_CUP);
전역에 변수를 선언해야 하는 경우는 최대한 없애는 것이 좋아요.
서로 연관이 없는 함수들 사이에서 "어쩔 수 없이" 해당 변수의 값을 가지고 로직을 처리해주어야 할 때, 전역 변수를 만드는 것이 좋습니다.

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +        newLocalWaterAmount = localWaterAmount + (waterAmount*ONE_CUP);
예를 들어서 waterAmount는 현재 물의 양을 각 함수들이 알아야 하니까 전역에 선언하는 것이 맞겠죠.

2022-01-29 10:36 UTC, Puterism commented on js/app.js
> +        alert("0 미만으로 줄일 수 없습니다.");
좋은 예외 처리네요 👍

2022-01-29 10:36 UTC, Puterism commented on index.html
>  </body>
요건 가볍게 숙제를 드릴게요
![image](https://user-images.githubusercontent.com/2542730/151657693-a5065baa-8075-4267-ace0-a2f0315900a6.png)

Github에서는 파일의 맨 마지막에 개행하지 않으면 요런 경고를 주는데요. 왜 이런 경고를 주는 걸까요? 왜 각 파일에 개행을 해두는 게 좋을까요?

2022-01-31 01:25 UTC, doria-re commented on js/app.js
> +    if (currentUnit === "컵"){
잘 이해가 안가서 질문드립니다. 근데 그러면 어차피 DOM에 접근한다는 점에서 성능개선에 차이가 없지 않을까요? 그리고 단위를 보여주는 html 요소를 만든다는게 unit class에 포함된 모든 태그의 innerText에 존재하는 단위 부분을 분리시키라는 말일까요?

2022-01-31 01:26 UTC, doria-re commented on js/app.js
> +getWater();
정리하겠습니다!

2022-01-31 01:34 UTC, doria-re commented on index.html
>  </body>
찾아보니까 POSIX명세 문제라고 하네요 더 공부해보겠습니다!

2022-01-31 01:34 UTC, merged

2022-01-31 04:29 UTC, Puterism commented on js/app.js
> +    if (currentUnit === "컵"){
아, 이 부분은 제가 `innerText`를 계속 참조한다고 잘못 생각해서 코멘트를 드렸네요 😅  죄송합니다 ㅠㅠ

2022-01-31 04:31 UTC, Puterism commented on js/app.js
> +    if (currentUnit === "컵"){
개선해주신 코드 형태도 좋으니 이 부분은 넘어가셔도 좋을 것 같습니다!